---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test5-argocd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test5-argocd 
  name: test5-argocd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi